language: node_js
node_js:
- '0.10'
deploy:
  provider: releases
  api_key:
    secure: LifWcMvVdfecAE8MwECByqgoJZzjzlbO+0TedFZZ/zP+llfE024QAWluSpL6VrZTvqiAgPUj1M7H2YhxIGfoecnBZSHR+65BMDABFkQ/5Q+yH12iRDLK9bvjr+ToXSe7ia/MAtr08Ma9Z4yCNIOrnb003Liupq/NgNWJL+KQeQk=
  file:
    - dist\indexeddbmock.js
    - dist\indexeddbmock.min.js
  on:
    repo: kristofdegrave/indexedDBmock
